version: '3'
volumes:
  postgres_data: { }

services:
  bootpay_js_sdk_dev:
    image: docker.bootpay.co.kr/bootpay/bootpay-js-sdk:dev
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./:/var/www/
    ports:
      - "10013:3001"
    extra_hosts:
      "test-database": 10.0.100.2